// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnyomvzohtbrvzyivbmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueW9tdnpvaHRicnZ6eWl2Ym15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjgxMzYsImV4cCI6MjA3MzcwNDEzNn0.d3iy8Mp4zkRxq5JLNPyoBpaPvTvrGwbqUoW_oG5P_hE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});